[17/Apr/2014 13:39:47] ERROR [django.request:226] Internal Server Error: /ozio/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edwin/Programming/git-repo/edhome/edhome/ozio/views.py", line 37, in ozio_home
    return render(request, 'ozio/ozio_home.html', context)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader.py", line 141, in get_template
    template = get_template_from_string(template, origin, template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader_tags.py", line 263, in do_include
    isolated_context=isolated_context)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
django.template.base.TemplateDoesNotExist: ozio/ozio_dialog_trans.html
